initial.dbms.default_database=neo4j
db.query.default_language=CYPHER_25
server.directories.data=C:/Users/ohuan/Downloads/LLP Project/LocalNeo4j/storage/data
server.directories.logs=C:/Users/ohuan/Downloads/LLP Project/LocalNeo4j/storage/logs
server.directories.run=C:/Users/ohuan/Downloads/LLP Project/LocalNeo4j/storage/run
server.directories.import=C:/Users/ohuan/Downloads/LLP Project/LocalNeo4j/storage/import
server.directories.plugins=C:/Users/ohuan/Downloads/LLP Project/LocalNeo4j/storage/plugins
dbms.security.auth_enabled=false
dbms.usage_report.enabled=false
server.default_listen_address=127.0.0.1
server.default_advertised_address=localhost
server.bolt.enabled=true
server.bolt.listen_address=:7690
server.bolt.advertised_address=:7690
server.http.enabled=true
server.http.listen_address=:7477
server.http.advertised_address=:7477
server.https.enabled=false
server.memory.heap.initial_size=256m
server.memory.heap.max_size=512m
server.memory.pagecache.size=128m
dbms.memory.transaction.total.max=128m
server.jvm.additional=-Djava.io.tmpdir=C:/Users/ohuan/Downloads/LLP Project/LocalNeo4j/storage/tmp
